# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants
  # [depth, width, max_channels]
  s: [0.33, 0.50, 1024]

# RRENet
backbone:
  # [from, repeats, module, args]
  - [-1, 1, RRLCBA, [64, 3, 2, 1]] # 0-P1/2
  - [-1, 1, PDRRECBA, [128, 3, 2, 1]] # 1-P2/4
  - [-1, 3, PDRREBlock, [128]]
  - [-1, 1, PDRRECBA, [256, 3, 2, 1]] # 3-P3/8
  - [-1, 6, PDRREBlock, [256]]
  - [-1, 1, PDRRECBA, [512, 3, 2, 1]] # 5-P4/16
  - [-1, 6, PDRREBlock, [512]]
  - [-1, 1, PDRRECBA, [512, 3, 2, 1]] # 7-P5/32
  - [-1, 3, PDRREBlock, [512]]
  - [-1, 1, GSPPF, [512, 5]] # 9

# rredet fpn+pan
head:
  - [-1, 1, PDRREUp, [256]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, PDRREBlock, [512]] # 12

  - [-1, 1, PDRREUp, [256]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, PDRREBlock, [256]] # 15 (P3/8-small)

  - [-1, 1, PDRRECBA, [256, 3, 2, 1]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, PDRREBlock, [512]] # 18 (P4/16-medium)

  - [-1, 1, PDRRECBA, [512, 3, 2, 1]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, PDRREBlock, [1024]] # 21 (P5/32-large)

  - [ 15, 1, GMaxPooling, [ 256 ] ]
  - [ 18, 1, GMaxPooling, [ 512 ] ]
  - [ 21, 1, GMaxPooling, [ 1024 ] ]
  - [[22, 23, 24], 1, Detect, [nc]] # Detect(P3, P4, P5)


